name: "Setup Environment"
description: "Setup Environment for Testing"
inputs:
  python-version:
    required: true
  poetry-flags:
    description: 'Poetry flags'
    required: false
    default: ''
runs:
  using: composite
  steps:
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true

    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'poetry'

    - name: Install dependencies
      shell: bash
      run: poetry install -vv ${{ inputs.poetry-flags }} --no-interaction

