version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: Pydiverse23
      POSTGRES_PORT: 6543
    ports:
      # keep port 5432 free since prefect 1 UI also spins up a postgres database on this port
      - 6543:5432
  mssql:
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: PydiQuant27
    ports:
      - 1433:1433
