services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: Pydiverse23
    ports:
      - "6543:5432"
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: PydiQuant27
    ports:
      - "1433:1433"
  ibm_db2:
    platform: linux/x86_64
    image: icr.io/db2_community/db2
    privileged: true
    environment:
      LICENSE: accept
      DB2INSTANCE: db2inst1
      DB2INST1_PASSWORD: password
      DBNAME: testdb
      UPDATEAVAIL: NO
    ports:
      - 50000:50000
