name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  linux-unittests:
    name: "Linux - unit tests - Python ${{ matrix.PYTHON_VERSION }}"
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        PYTHON_VERSION: ['3.8', '3.9', '3.10']
    steps:
      - name: Docker login
        run: docker login ghcr.io -u "${{ github.actor }}" -p "${{ secrets.GITHUB_TOKEN }}"
      - name: Pull image
        run: docker pull ghcr.io/quantco/qc-mambaforge-base:latest
      - name: Checkout branch
        uses: actions/checkout@v3.0.2
        with:
          ref: ${{ github.head_ref }}
      - name: Fetch full git history
        run: git fetch --prune --unshallow
      - name: Checkout github-actions repo
        uses: actions/checkout@v3.0.2
        with:
          repository: Quantco/github-actions
          ref: main
          token: ${{ secrets.FQ_GH_TOKEN }}
          path: .github/quantco-actions
      - name: Run unit tests inside of container
        uses: ./.github/quantco-actions/unittests
        with:
          python_version: ${{ matrix.PYTHON_VERSION }}
          src_folder: "pydiverse.transform"
          run_parallel: "false"
          conda_api_key: "${{ secrets.QUETZ_API_KEY }}"

  docs:
    name: "Documentation - build & upload"
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Docker login
        run: docker login ghcr.io -u "${{ github.actor }}" -p "${{ secrets.GITHUB_TOKEN }}"
      - name: Pull image
        run: docker pull ghcr.io/quantco/qc-mambaforge-base:latest
      - name: Checkout branch
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/checkout@v3.0.2
      - name: Checkout plain HEAD commit
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/checkout@v3.0.2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Fetch full git history
        run: git fetch --prune --unshallow
      - name: Checkout github-actions repo
        uses: actions/checkout@v3.0.2
        with:
          repository: Quantco/github-actions
          ref: main
          token: ${{ secrets.FQ_GH_TOKEN }}
          path: .github/quantco-actions
      - uses: google-github-actions/setup-gcloud@v0.6.0
        with:
          version: '354.0.0'
          project_id: ${{ secrets.GCP_UPLOAD_PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_UPLOAD_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_UPLOAD_SA_KEY }}
          export_default_credentials: true
      - name: Run doc build inside of container
        uses: ./.github/quantco-actions/docs
        with:
          conda_api_key: "${{ secrets.QUETZ_API_KEY }}"
      - name: Publish Docs
        if: ${{ github.event_name != 'pull_request' }}
        run: cd docs/_build/html && gsutil -m cp -r * gs://qc-github-artifacts/${GITHUB_REPOSITORY}/${GITHUB_SHA}/
      - name: Publish Docs
        if: ${{ github.event_name == 'pull_request' }}
        run: cd docs/_build/html && gsutil -m cp -r * gs://qc-github-artifacts/${GITHUB_REPOSITORY}/${{ github.event.pull_request.head.sha }}/
      - name: Publish Docs as latest
        run: cd docs/_build/html && gsutil -m cp -r * gs://qc-github-artifacts/${GITHUB_REPOSITORY}/latest/
        if: github.ref == 'refs/heads/main'

  pre-commit-checks:
    name: "Linux - pre-commit checks - Python 3.8"
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3.0.2
        with:
          ref: ${{ github.head_ref }}
      - name: Install Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Run pre-commit checks
        uses: pre-commit/action@v2.0.3

  linux-conda-build:
    name: "Linux - conda-build - Python ${{ matrix.PYTHON_VERSION }}"
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        PYTHON_VERSION: ['3.8']
    steps:
      - name: Docker login
        run: docker login ghcr.io -u "${{ github.actor }}" -p "${{ secrets.GITHUB_TOKEN }}"
      - name: Pull image
        run: docker pull ghcr.io/quantco/qc-mambaforge-base:latest
      - name: Checkout branch
        uses: actions/checkout@v3.0.2
        with:
          ref: ${{ github.head_ref }}
      - name: Fetch full git history
        run: git fetch --prune --unshallow
      - name: Checkout github-actions repo
        uses: actions/checkout@v3.0.2
        with:
          repository: Quantco/github-actions
          ref: main
          token: ${{ secrets.FQ_GH_TOKEN }}
          path: .github/quantco-actions
      - name: Run conda-build inside of container
        uses: ./.github/quantco-actions/conda-build
        with:
          python_version: ${{ matrix.PYTHON_VERSION }}
          conda_api_key: "${{ secrets.QUETZ_API_KEY }}"
