name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  release:
    name: 'Build and Release on PyPi'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup Environment
        uses: ./.github/actions/setup
        with:
          python-version: '3.11'
      
      - name: Build
        run: poetry build

      - name: Check distributions
        run: ls -la dist

      - name: Publish to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: poetry publish

